[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
set runtimepath+=~/.cache/dein/repos/github.com/vim-airline/vim-airline-themes/
let g:airline_theme = 'deus'
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
"refered https://original-game.com/vim-airline/
let g:airline#extensions#tabline#enabled = 1
nmap <Leader><Tab> <Plug>AirlineSelectPrevTab<CR>
nmap <Tab> <Plug>AirlineSelectNextTab<CR>

let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#tabline#left_sep = '|'
let g:airline_mode_map = {
    \ 'n' : 'N',
    \ 'i' : 'I',
    \ 'R' : 'R',
    \ 'c' : 'C',
    \ 'v' : 'V',
    \ 'V' : 'VL',
\}
  let g:airline_left_sep = '»'
  let g:airline_left_sep = '▶'
  let g:airline_right_sep = '«'
  let g:airline_right_sep = '◀'
"let g:airline_right_sep = ''
"let g:airline_right_alt_sep = ''
"let g:airline_left_sep = ''
"let g:airline_left_alt_sep = ''
"let g:airline_symbols.crypt = ''
"let g:airline_symbols.linenr = ''
"let g:airline_symbols.maxlinenr = ''
"let g:airline_symbols.branch = ''
"let g:airline_symbols.paste = ''
"let g:airline_symbols.spell = ''
"let g:airline_symbols.notexists = ''
"let g:airline_symbols.whitespace = ''
let g:airline#extensions#default#layout = [
\ [ 'a', 'b', 'c' ],
\ [ 'x', 'y', 'z', 'error', 'warning']
\ ]
let g:airline#ectensions#tabline#show_close_button = 1
let g:airline#extensions#tabline#close_symbol = 'X'
autocmd VimEnter * AirlineRefresh
'''
