[[plugins]] # lint tool
repo = 'dense-analysis/ale'
hook_add = '''
set runtimepath+=~/.cache/dein/repos/github.com/dense-analysis/ale/
let g:ale_sign_column_always = 1
"let g:ale_php_phpcs_standard = '~/phpcs.xml,PSR1,PSR2'
"let g:ale_php_phpcbf_standard = '~/phpcs.xml'

let g:ale_fixers = {
\ 'php': ['phpcbf'],
\}
let g:ale_fix_on_save = 1
let g:ale_lint_on_text_changed = 0
"lint
let g:ale_linters = {
  \'javascript': ['eslint'],
  \'ruby': ['rubocop', 'reek'],
  \'php': ['phpcs', 'phpcbf'],
  \'Dockerfile': ['dockerfile_lint', 'hadolint'],
  \'scss': ['stylelint']
\}
let g:ale_dockerfile_hadolint_use_docker = 'enable'
let g:ale_scss_stylelint_use_global = 1
" let g:ale_sign_error = ''
" let g:ale_sign_warning = ''
let g:airline#extensions#ale#open_lnum_symbol = '('
let g:airline#extensions#ale#close_lnum_symbol = ')'
let g:ale_echo_msg_format = '[%linter%]%code: %%s'
highlight link ALEErrorSign Tag
highlight link ALEWarningSign StorageClass
nmap <silent> <C-w>k <Plug>(ale_previous_wrap)
nmap <silent> <C-w>j <Plug>(ale_next_wrap)
'''
hook_post_source = '''
let g:ale_linters = {
  \'Dockerfile': ['dockerfile_lint', 'hadolint']
\}
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
